import { Inter } from 'next/font/google'
import { TextToSpeech } from "@/components/TextToSpeech";
import { IsPlayingProvider } from "../pages/context/isPlayingContext";
import { ChatBotCanvas } from "../components/ChatBotCanvas";
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen">
			<IsPlayingProvider>
				<TextToSpeech />
				<ChatBotCanvas />
			</IsPlayingProvider>
		</main>

    </>
  )
}
